chain=elementsregtest
server=1
txindex=1
listen=1
fallbackfee=0.00001
validatepegin=0

mainchainrpchost=bitcoind
mainchainrpcport=18443
mainchainrpcuser=local_rpc
mainchainrpcpassword=local_rpc_password

[elementsregtest]
rpcbind=0.0.0.0
rpcallowip=0.0.0.0/0
rpcport=7041
rpcuser=user
rpcpassword=pass
port=7042
initialfreecoins=2100000000000000
anyonecanspendaremine=1
